# Generated by Django 3.2.16 on 2022-12-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('formula', models.CharField(max_length=50)),
                ('boiling_point', models.DecimalField(decimal_places=8, max_digits=8)),
                ('melting_point', models.DecimalField(decimal_places=8, max_digits=8)),
                ('phase_at_room_temperature', models.CharField(choices=[('S', 'Solid'), ('L', 'Liquid'), ('G', 'Gas'), ('P', 'Plasma')], max_length=10)),
                ('density', models.DecimalField(decimal_places=8, max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
