# Generated by Django 3.2.16 on 2022-12-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='boiling_point',
            field=models.DecimalField(decimal_places=8, max_digits=16),
        ),
        migrations.AlterField(
            model_name='compound',
            name='density',
            field=models.DecimalField(decimal_places=8, max_digits=16),
        ),
        migrations.AlterField(
            model_name='compound',
            name='melting_point',
            field=models.DecimalField(decimal_places=8, max_digits=16),
        ),
    ]
