# Generated by Django 3.2.16 on 2022-12-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0003_auto_20221226_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='members',
        ),
        migrations.AddField(
            model_name='compound',
            name='stores',
            field=models.ManyToManyField(related_name='stores', through='compounds.CompoundStore', to='compounds.Store'),
        ),
    ]
