# Generated by Django 3.2.16 on 2022-12-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0004_auto_20221228_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='molar_mass',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
            preserve_default=False,
        ),
    ]
