# Generated by Django 3.2.16 on 2022-12-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0006_compoundstore_compound_store_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='stores',
            field=models.ManyToManyField(related_name='compounds', through='compounds.CompoundStore', to='compounds.Store'),
        ),
    ]
