# Generated by Django 3.2.16 on 2023-01-01 14:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0007_alter_compound_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='gps_coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=8, max_digits=16), default=[0, 0], size=2),
            preserve_default=False,
        ),
    ]
