# Generated by Django 3.2.16 on 2022-12-30 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compounds', '0006_compoundstore_compound_store_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('temperature', models.DecimalField(decimal_places=8, max_digits=16)),
                ('pressure', models.DecimalField(decimal_places=8, max_digits=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReactionCompound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stoichiometry', models.DecimalField(decimal_places=8, max_digits=16)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.compound')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactions.reaction')),
            ],
        ),
        migrations.AddField(
            model_name='reaction',
            name='compounds',
            field=models.ManyToManyField(related_name='reactions', through='reactions.ReactionCompound', to='compounds.Compound'),
        ),
        migrations.AddConstraint(
            model_name='reactioncompound',
            constraint=models.UniqueConstraint(fields=('compound', 'reaction'), name='compound_reaction_unique'),
        ),
    ]
